package com.tilicho.grocery.mangement.viewModel

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import com.tilicho.grocery.mangement.sharedPreferences.AppPreff


class SettingsViewModel(application: Application) : AndroidViewModel(application) {

    private val _autogeneratedDate: MutableLiveData<String> = MutableLiveData("28/09/2021")
    val autogeneratedDate: LiveData<String>
        get() = _autogeneratedDate

    private val _launchScreen: MutableLiveData<String> = MutableLiveData("Home")
    val launchScreen: LiveData<String>
        get() = _launchScreen

    private val _appearenceType: MutableLiveData<String> = MutableLiveData("Light")
    val appearenceType: LiveData<String>
        get() = _appearenceType

    private val _email: MutableLiveData<String> = MutableLiveData(AppPreff(application).getUserEmail())
    val email: LiveData<String>
        get() = _email
    private val _name: MutableLiveData<String> = MutableLiveData(AppPreff(application).getFirstName() +" "+ AppPreff(application).getLastName())
    val name: LiveData<String>
        get() = _name
}